### ISSUE TITLE
Clarify that VeraDemo is intentionally vulnerable

### ISSUE THREAD

**Issue by tjarrettveracode** [veracode/verademo#27]
The description of this project talks about an intentionally vulnerable web app, but the README file just talks about the "Blab-A-Gag" app. Because we sometimes get actual vulnerability reports about this app, we should consider doing the following:

* Update the README file to clearly state that this is an intentionally vulnerable project
* Update the parts of the source code that comment something as /* BAD CODE */ to say something like /* EXAMPLE VULNERABILITY */ or something along these lines

**Comment by rlarkin01** [comment]
the /* bad code */ ... /* good code*/ notations are also extremely valuable for product demos when we are showing tools like the IDE scan, like we have in places on Verademo.NET: https://github.com/veracode/verademo-dotnet/blob/main/Verademo-Dotnet/Controllers/HomeController.cs
